Controllers films users
BlackBox15/java-filmorate pull request #5
Opened 2024-03-03 21:32 UTC by BlackBox15

2024-03-04 05:26 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    List<Film> films = new ArrayList<>();
модификатор доступа

2024-03-04 05:27 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    List<User> users = new ArrayList<>();
модификатор доступа

2024-03-04 05:29 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .filter(item -> item.getId() == user.getId())
мапу использовать было бы эффективней

2024-03-04 05:32 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isEmpty() || !(user.getEmail().contains("@"))) return false;
если вместо false кидать исключение, то в месте вызова код будет менее загроможден
например
```
   public User create(@RequestBody User user) throws ValidationException {
        validateUser(user));
        user.setId(++userId);
        users.add(user);
...
```

2024-03-04 05:34 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends IOException {
не удачно выбран базовый класс, т.к. валидация никак не связана с ошибками ввода-вывода

2024-03-04 05:35 UTC, VadimZharkov requested changes
Нужно исправить замечания и добавить тесты для валидации (согласно ТЗ)

2024-03-05 07:05 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    List<Film> films = new ArrayList<>();
исправил

2024-03-05 07:13 UTC, VadimZharkov approved these changes

2024-03-22 08:54 UTC, merged